### ISSUE TITLE
why I stuck in the "create web directory ./checkpoint/males_model/web..."

### ISSUE THREAD

**Issue by AMG024** [royorel/Lifespan_Age_Transformation_Synthesis#19]
I run the train.bat, but the code stuck in the "create web directory ./checkpoint/males_model/web..." like the picture show
![WeChat Image_20210427225417](https://user-images.githubusercontent.com/46367833/116262913-83f43d00-a7ab-11eb-9cac-a3ecd68aef7a.jpg)

**Comment by royorel** [comment]
Hi @AMG024 ,

This seems very weird, but I need more information in order to help you.
What line does the program stops in when you break it (Ctrl+c) ?

**Comment by AMG024** [comment]
Thanks for your replay, @royorel,  the program stuck has lasted all day before break it. And I break it(Ctrl+c), the program show on the picture
![a](https://user-images.githubusercontent.com/46367833/116338713-c3a04080-a80e-11eb-97f3-621a8e8710a2.PNG)

**Comment by royorel** [comment]
@AMG024 

It looks like your system has some issue with multiprocessing. Try changing num_workers below to 0 and see if it goes through. 
https://github.com/royorel/Lifespan_Age_Transformation_Synthesis/blob/7be4534848e94d9493dfb6da8dfd5724fa5f6766/data/data_loader.py#L19

If it does go through after changing it to 0, it's indeed a multiprocessing issue specific to your system, I would suggest to try setting nThreads to a lower number (the default is 4).

If nothing works and you end up running with `num_workers=0` keep in mind the runtime will significantly increase

**Comment by AMG024** [comment]
@royorel, I reset the num_workers to 0, and wait for a couple of hours, but it still not works, How long does it takes to load all data? And is it due to the equipment, I only use a  gpu, rtx 5000.

**Comment by royorel** [comment]
Once again, I need to see the python output.

Generally speaking, this doesn't seem like a GPU issue. The data loading is a CPU process

**Comment by AMG024** [comment]
@royorel the python output is the same as the two picture above

**Comment by AMG024** [comment]
> @royorel the python output is the same as the two picture above

**Comment by royorel** [comment]
That seems weird, when using num_workers=0 multiprocessing is off, so there's reason for the python multiprocessing library to be invoked in such case

**Comment by AMG024** [comment]
![捕获_1](https://user-images.githubusercontent.com/46367833/116383211-36c6a880-a849-11eb-978b-3c6780e39ed0.PNG)
this is the break(Ctrl c) output

**Comment by royorel** [comment]
That means the data is being loaded, maybe very slow, but it does load.

Right now it looks like this is a specific issue with your machine and not an issue with the code

**Comment by AMG024** [comment]
@royorel , I sorry to trouble you, but I want to konw why I can run the train.py. I put a step-by-step print, and I find when run in the line 74, it stuck, and can not print i and data
![Capture](https://user-images.githubusercontent.com/46367833/116515301-ad71ad80-a8fe-11eb-830a-38ef3b8218fe.PNG)
I print the dataset on the previous line, it can print a DataLoader object, the data should be loaded
![捕获_2](https://user-images.githubusercontent.com/46367833/116516019-a6976a80-a8ff-11eb-9c2d-90545fa51635.PNG)

**Comment by AMG024** [comment]
@royorel , I don`t say the fault of your code, but I have some problem of your code. like, when I run the code, why it has a warning show on the picture
![捕获_3](https://user-images.githubusercontent.com/46367833/116526475-38a57000-a90c-11eb-8095-6f6e2c7eccf4.PNG)
