### ISSUE TITLE
RuntimeError : CUDA out of memory

### ISSUE THREAD

**Issue by farzadmohseni-ir** [royorel/Lifespan_Age_Transformation_Synthesis#20]
**When I run `./run_scripts/in_the_wild.bat`**

I get the following error

> RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 4.00 GiB total capacity; 960.24 MiB already allocated; 1.90 MiB free; 2.47 GiB reserved in total by PyTorch)

![image](https://user-images.githubusercontent.com/57835828/118917636-8aa74780-b946-11eb-89c6-5d0414144a50.png)

Please help to fix the error

**Comment by royorel** [comment]
That error means that you GPU doesn't have enough memory to store all the necessary data. The only thing you can do beside upgrading your GPU is this:

Run `./run_scripts/in_the_wild.bat` with `--interp_step` larger than 0.05. Increase this number until your GPU can fit the data into its memory. The down side is that the output video will have less frames and therefore more jittery
