### ISSUE TITLE
Number of age bins

### ISSUE THREAD

**Issue by ujjayants** [royorel/Lifespan_Age_Transformation_Synthesis#22]
I noticed that you used 6 age bins to train. Would it be an issue if the bins are increased moderately, say to 7?
Or would you recommend training two models, covering 3 and 4 bins respectively ?

**Comment by royorel** [comment]
Hi @ujjayants,

Sorry I missed your question. I think increasing the training to 7 age bins should work fine, assuming the extra age bin is distinct from the rest. For instance an added bin for ages 70+.
