### ISSUE TITLE
Continue Training Missing File 

### ISSUE THREAD

**Issue by voetberg** [royorel/Lifespan_Age_Transformation_Synthesis#24]
Hello, and thank you for sharing your work. 

While attempting to use the continue training flag, I noticed two issues. 

Firstly, when picking up from a previously run model, if the number of epochs specified is smaller than the amount already run, the model initializes and does not run without any explanation. After figuring out the number of epochs to continue training need to be added to the number previously run, it works fine, but this is very confusing and could be better explained in the documentation or the options. 

Secondly, (and more critically) when that continue train flag is set, the model loader looks for two files named "<which_epoch>_net_<G/D>_tex.pth" in the model checkpoints folder. While a version without the '_tex' exists, neither of the _tex files do. Attempting to run as is produces the error: 

```
 ./checkpoints/<model>/latest_net_G_tex.pth not exists yet!
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    train(opt)
  File "train.py", line 42, in train
    model = create_model(opt)
  File "Lifespan_Age_Transformation_Synthesis/models/models.py", line 12, in create_model
    model.initialize(opt)
  File "Lifespan_Age_Transformation_Synthesis/models/LATS_model.py", line 94, in initialize
    self.load_network(self.netG, 'G_tex', opt.which_epoch, pretrained_path)
  File "Lifespan_Age_Transformation_Synthesis/models/base_model.py", line 62, in load_network
    raise('Generator must exist!')
TypeError: exceptions must derive from BaseException
```

This can be circumvented by renaming the existing network files to fit this naming scheme, but it concerns me none of the less. What is this _tex file? Should it have been generated or is it a naming scheme from a previous version? 

My command for producing the error is below: 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --gpu_ids 0,1,2,3 --dataroot /data/ --name <model> --batchSize 16 --verbose --epochs 10 --save_epoch_freq 5 --continue_train --which_epoch latest
```

**Comment by royorel** [comment]
Hi @voetberg,

Thanks for catching that! 

I will rewrite readme.MD and the options documentation accordingly.

Regarding the '_tex' suffix, it's just a previous naming convention from an earlier version of the code that I forgot to remove for the published version. I updated `LATS_model.py` accordingly and removed the `_tex` suffix.
