### ISSUE TITLE
Making a good video with a not very powerfull graphic card

### ISSUE THREAD

**Issue by Francyrad** [royorel/Lifespan_Age_Transformation_Synthesis#25]
Dear Developers

I posse a GTX 950 M and i can only make 1-2 second long video with a "bad" quality. This is because i can set only a timestep of 0.15-2.

I ask if in the future it will be possible to make very good videos, like the gifs you posted, just making work the graphic card for a longer time. This is only to avoid the renting of a GPU cloud or buying a new graphic card, because of the actual crisis caused by COVID and mining that let a rising of prices.

Let us know!

**Comment by royorel** [comment]
Hello @Francyrad,

We don't plan to pursue this direction. But there are 2 ways to bypass this issue:
1. Use google colab, where you get a stronger GPU for free
2. Wrap the following line in a for loop that will process the maximum number of frames your GPU can handle each time.
https://github.com/royorel/Lifespan_Age_Transformation_Synthesis/blob/022b8c1b1c6e50726b3a4b87f4eb88ce1b892e99/models/LATS_model.py#L408
