### ISSUE TITLE
CUDA out of memory when running the demo.

### ISSUE THREAD

**Issue by zlq1z2l3q** [royorel/Lifespan_Age_Transformation_Synthesis#26]
Hi, thanks for sharing your nice work and the dataset. I am playing around your code to know more about your idea. But when running the demo locally or on Google colab, it randomly prompts CUDA out of memory like this:
![Screenshot at 17-12-11](https://user-images.githubusercontent.com/18570724/141613152-406b1979-fb16-4604-b80c-a2a0f692723f.png)
I have not changed anything of your code. Do you have any idea about that? Thanks a lot.

**Comment by royorel** [comment]
Hi @zlq1z2l3q,

Sometimes Google colab allocates GPUs with smaller RAM size. Please see issue #23 for the solution.

**Comment by zlq1z2l3q** [comment]
Ah, I didn't notice the issue before, thank you very much!
