### ISSUE TITLE
Error in running the demo of google colab

### ISSUE THREAD

**Issue by EddyRonald** [royorel/Lifespan_Age_Transformation_Synthesis#27]
Good morning dear developers, I have tried to run the demo that you provide in google colab but I have had an error about the CUDA memory, one more specification is that the error occurs in the following cell of the cell where the photo is uploaded:

data = dataset.dataset.get_item_from_path(img_path)
visuals = model.inference(data)           <--------------- Here the error occurs

RuntimeError: CUDA out of memory. Tried to allocate 3.16 GiB (GPU 0; 11.17 GiB total capacity; 5.69 GiB already allocated; 758.81 MiB free; 9.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I have been following the instructions that you give to upload the photo, I do not think that is the problem but in the same way I leave the image that I have uploaded (this image belongs to the UTKFace dataset)
![0001_1](https://user-images.githubusercontent.com/26469422/146587586-99ba171c-8d42-4100-8edc-97e6f8934363.jpg)

I hope you can help me, thank you

**Comment by royorel** [comment]
Hi @EddyRonald,

Watch issue #23 for the solution

**Comment by EddyRonald** [comment]
Thanks !
