### ISSUE TITLE
Error in colab

### ISSUE THREAD

**Issue by dfrumkin** [royorel/Lifespan_Age_Transformation_Synthesis#3]
Hello!  

I wanted to test your code in the colab.  Everything worked fine, uploaded the file, but then there was some problem reading it:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8c3f4407a6b4> in <module>()
----> 1 data = dataset.dataset.get_item_from_path(img_path)
      2 visuals = model.inference(data)
      3 
      4 os.makedirs('results', exist_ok=True)
      5 out_path = os.path.join('results', img_path[:-4] + '.mp4')

2 frames
/content/Lifespan_Age_Transformation_Synthesis/util/preprocess_itw_im.py in extract_face_landmarks(self, img)
     94 
     95         # Get the landmarks/parts for the face in box d.
---> 96         dlib_shape = self.predictor(img, dets[max_idx])
     97         landmarks = self.dlib_shape_to_landmarks(dlib_shape)
     98         return landmarks

TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.rectangles, s: slice) -> dlib.rectangles
    2. (self: dlib.rectangles, arg0: int) -> dlib.rectangle

Invoked with: rectangles[], -1
```

**Comment by royorel** [comment]
Hi Dmitry,

Thank you for your email. It looks like there’s an issue with the dlib face
detector. My best guess is that it wasn’t able to detect a face in the
image, but I’m not entirely sure

Would you mind sendIng me the image to see if I can reproduce the error?

Best,
Roy

**Comment by dfrumkin** [comment]
Hello Roy!

Sorry for not replying earlier.  Indeed the problem was with the face being too small; I took another image and everything worked.  Perhaps you could give a more informative error message.  Thank you!

Dmitry

**Comment by royorel** [comment]
The error is invoked from the dlib library. I'll see whether I can wrap it and give a more informative error

**Comment by royorel** [comment]
I added a more informative error message for that case in commit ba55a40
