### ISSUE TITLE
Solution for wrongly generated hair color/race

### ISSUE THREAD

**Issue by longsc2603** [royorel/Lifespan_Age_Transformation_Synthesis#37]
Hi there,
I tried using a picture of my grandpa (97 years old, hair all white) in your Colab notebook. It generated a video of my grandpa with white/blonde hair as a kid (an American kid), but he is Asian. Now is there a solution for this? Or is there any flag in the model regarding hair color/race/eye color that I don't know about?
I hope you guys can reply soon, thank you in advanced.

**Comment by royorel** [comment]
Unfortunately there's not too much you can do about it. You can maybe try to rerun the code since there is some randomness to input latent vector coming from the target age group, but I would expect any major change.
