### ISSUE TITLE
i want to generate 6 images only not the video 

### ISSUE THREAD

**Issue by mohamedmonem14** [royorel/Lifespan_Age_Transformation_Synthesis#39]
hoe to generate six images only not the gif video and how to download the model as pkl file to use it

**Comment by royorel** [comment]
Hi @mohamedmonem14,

Detailed instructions can be found in the readme file. It's in the testing -> generate full progression section.

**Comment by mohamedmonem14** [comment]
i want to generate only 6 images correspondings to the 6 classes the full
progression creates 120 image

**Comment by mohamedmonem14** [comment]
> how to generate six images only not the gif video and how to download the model as pkl file to use it

**Comment by mohamedmonem14** [comment]
> Hi @mohamedmonem14,
> 
> Detailed instructions can be found in the readme file. It's in the testing -> generate full progression section.

i want it using quick demo in colab

**Comment by royorel** [comment]
Are you using colab? The instructions refer to running from command line. If you're running from colab, set 'opt.traverse = False', add a line 'opt.deploy = True', replace 'visualizer.make_video' with 'visualizer.save_row_image' and change the 'out_path' suffix from 'mp4' to 'png'.

**Comment by mohamedmonem14** [comment]
![abdelrhman](https://github.com/royorel/Lifespan_Age_Transformation_Synthesis/assets/103948638/5e47b6da-694e-4ad8-827b-22456eebbbf7)
now it creates one image contains the 7 save image, i want every image to be saved separately

**Comment by royorel** [comment]
To save every image separately, replace 'util.save_row_image' with 'util.save_images_deploy' and remove the file suffix from 'out_path'. 'out_path' should just be a template name e.g. 'results/image000'

**Comment by mohamedmonem14** [comment]
thank you it helped me , i have another question i want to save the entire model in my device as pkl file then use it in my app what should i do since im using colab

**Comment by royorel** [comment]
You can download the saved model directly to your machine using the download script. (Or download manually using the links)

**Comment by mohamedmonem14** [comment]
whick link contains the model

**Comment by royorel** [comment]
The links are in the download script. Alternatively you can just download the model weights from the colab.

**Comment by mohamedmonem14** [comment]
how to download the model weights from the colab?

**Comment by mohamedmonem14** [comment]
hello i want instead of cloning repo of github every time i use the demo in colab i want to download the model in google drive then use it but i'm facing alot of errors what should i do ?

**Comment by SystemErrorWang** [comment]
> Are you using colab? The instructions refer to running from command line. If you're running from colab, set 'opt.traverse = False', add a line 'opt.deploy = True', replace 'visualizer.make_video' with 'visualizer.save_row_image' and change the 'out_path' suffix from 'mp4' to 'png'.

Hello I was also trying to generate fewer images on my own server, and when I disabled "traverse", the model just skipped generating images and finished right after initializing. Would you please give me some help?

**Comment by royorel** [comment]
If you're not using colab, please follow the instructions in the readme file. It's in the testing -> generate full progression section.
