### ISSUE TITLE
How i can get high quality images/video output?  it's blocked to 256 currently

### ISSUE THREAD

**Issue by putuoka** [royorel/Lifespan_Age_Transformation_Synthesis#4]
i have tried modify loadsize and finesize in base_options.py to 600 from 256 but nothing happen it still blocked default 256 only

**Comment by royorel** [comment]
Did it happen in colab? or when you tried to run one of the run scripts?
If it's one of the run scripts, which script was it?

Please provide more information, so I can figure out what went wrong

**Comment by putuoka** [comment]
> Did it happen in colab? or when you tried to run one of the run scripts?
> If it's one of the run scripts, which script was it?
> 
> Please provide more information, so I can figure out what went wrong

I try in colab but what i mean is it possible to make output other than 256? How to do that?

**Comment by royorel** [comment]
I was able to generate a 600x600 result by changing loadsize and finesize in base_options.py. 

However keep the following things at mind:
1. You might get an out of memory error. In that case, you should increase opt.interp_step until you the GPU can fit everything into memory
2. In the display output cell you will see this code:
```
HTML("""
<video width=256 controls>
      <source src="{0}" type="{1}">
</video>
""".format(data_url, video_type))
```
That means that the video is displayed at 256x256 resolution, but if you download it (in the last cell) you will see that the resolution is still 600x600. **I will change the width value to be opt.fineSize though, that's a good catch**.
3. The pre-trained models were trained on a 256x256 images only. I'm assuming the results would not have the same quality as the ones on 256x256 inputs. I would recommend to retrain the models if you want to use 600x600 images.

Let me know if there are still any open issues
